name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push tags and commits
      pull-requests: write # Needed to create the Version PR
      id-token: write

    steps:
      - name: â¬‡ï¸ Checkout Repo
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.24.0
          run_install: false

      - name: ğŸŸ¢ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: pnpm

      - name: ğŸ“¦ Install Dependencies
        run: pnpm -w install --frozen-lockfile

      - name: ğŸ”¨ Build
        run: pnpm -w build

      - name: ğŸš€ Create Release PR or Publish
        uses: changesets/action@v1
        with:
        # ğŸ‘‡ matches your "version-packages" script
            version: pnpm version-packages 
        
        # ğŸ‘‡ matches your "publish-packages" script
            publish: pnpm publish-packages 
            
            commit: "chore: version packages"
            title: "Version Packages"
        env:
        # Needs your GitHub Token (built-in) to create PRs
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Needs your NPM Token to publish
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}